### ISSUE TITLE
Paikallisten testien bugi.

### ISSUE THREAD

**Issue by Melchan** [ohtu-intellij/tmc-intellij#101]
windows 10
IntelliJ 2016.2

Paikalliset testit eivät toimineet seuraavissa eng. mooc  tehtävissä.
week 10, 34
week 11, 35

Heitän tän nytten tänne ku en oo varma minne muuallekkaan. Tossa on englantia puhuvalta mooc käyttäjältä tietoja siitä kun sillä ei toiminut paikalliset testit intellij plugarissa. 

Extra: 

week 11, 33  testit menivät läpi serverillä vaikka ei olisi pitänyt. (liian vähän testi keissejä kuulemma)

**Comment by cxcorp** [comment]
Antaako mitään virheviestiä?

**Comment by jippo444** [comment]
Raportoin tähän ketjuun oman samankaltaisen bugihavainnon (In English below):

Järjestelmä/System
Ubuntu 16.04 xenial (x86-64)
IntelliJ 2016.3

Paikalliset testit eivät ole toimineet millään hy-s2016-wepa -kurssin tehtävistä joissa olen niitä kokeillut. Esimerkkinä vaikkapa W6-57.LowestPrices.

TMC-plugin antaa välittömästi viestin "All tests passed! Would you like to submit the excercise?" vaikka tehtäväpohja on koskematon. Viesti tulee niin nopeasti, ettei plugin selvästi aja mitään testejä. Serverille lähetys (ja testit serverillä) ovat kyllä tomineet nähdäkseni oikein.

In English:
None of local tests have worked so far in course hy-s2016-wepa. This happens e.g. in exercise W6-57.LowestPrices. TMC Plugin just immediately prompts "All tests passed! Would you like to submit the excercise?" even though the excercise hasn't been completed. Submitting to server (and tests on server) seems to work correctly.

**Comment by cxcorp** [comment]
@jippo444 Samaa saan, avasin tuolle oman issuen #113 / Confirmed, I opened an issue for that.

**Comment by cxcorp** [comment]
@jippo444 Jos vaihdat environment variablen `JAVA_HOME`:n osoittamaan asennetun Java JDK:n kansioon JRE:n sijaan, lisäät jdk kansion bin-kansion `PATH`:iin, sitten käynnistät IDEAn uudestaan, toimivatko testit? Toimivatko testit jos avaat konsolin, navigoit testikansioon ja pyörität `mvn test`?

**Comment by jippo444** [comment]
Jos ajan tehtävän W6-57.LowestPrices testit konsolin kautta ('mvn test') tai hiiren oikealla näppäimellä testikansiosta ("Run 'All Tests'"), ne toimivat oikein. Results : Tests run: 2, Failures: 0, Errors: 0, Skipped: 0 Tehtävä on siis tässä vaiheessa tehty ja mennyt läpi myös serverillä, joten testien pitäisikin mennä läpi.

Kokeilin tätä myös tehtävässä W6-60.Reservations, jossa on enemmän testejä. Results : Tests run: 11, Failures: 0, Errors: 0, Skipped: 0. Kun teen tehtävään "bugin" (muutan koodia niin, että se kyllä kääntyy oikein, mutta ei toimi tehtävänannossa edellytetyllä tavalla), kaikki testit eivät mene läpi, kuten ei pitäisikään: 

Tests run: 11, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 8.06 sec <<< FAILURE! - in wad.controller.ReservationTest
overlappingReservationsAllowedForDifferentApartments(wad.controller.ReservationTest)  Time elapsed: 0.029 sec  <<< FAILURE!
java.lang.AssertionError: When two reservations have been posted to /reservations, they both should be added to the database. expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at wad.controller.ReservationTest.overlappingReservationsAllowedForDifferentApartments(ReservationTest.java:282)

ableToSetAsPaid(wad.controller.ReservationTest)  Time elapsed: 0.025 sec  <<< FAILURE!
java.lang.AssertionError: When two reservations have been posted to /reservations, they both should be added to the database. expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at wad.controller.ReservationTest.ableToSetAsPaid(ReservationTest.java:298)

SDK:na on ollut koko ajan Ubuntun mukana tullut java-1.8.0-openjdk-amd64. Jos SDK:na olisi JRE, kokemukseni mukaan projekteja ei pystyisi ylipäätään rakentamaan tai ajamaan.

Kokeiltuani, että testit toimivat tehtävässä W6-60.Reservations, jätin koodiin bugin, joka aiheutti kahden testin epäonnistumisen testejä ajettaessa, ja kokeilin vielä ajaa paikalliset testit TMC:n painikkeesta ja TMC:n valikosta. Molemmilla tavoilla tulos oli aiemmin kertomani: välitön ilmoitus että testit menivät läpi. Liitteenä vielä screenshot tilanteesta sen jälkeen, kun testit on ajettu TMC:n painikkeen kautta:
![screenshot from 2016-12-18 11-11-47](https://cloud.githubusercontent.com/assets/19758400/21292558/cbfc6c92-c512-11e6-8f1e-e3b032811fcb.png)

**Comment by rlmhermans** [comment]
Excuse me for intruding in English, but I have the same issue as mentioned above. Even if all sources build and tests on the server fail, local tests wil pass without running when using the plugin 'Run Tests' menu item, or the toolbar button. If I run the tests using IntelliJ functionality, they fail as expected.

**Comment by rlmhermans** [comment]
I have cloned the repository and ran the plugin in the IntelliJ sandbox. It works properly there. I built and ran it using the 2017.1.3 plugin SDK.

**Comment by cxcorp** [comment]
@rlmhermans After setting up the test environment, can you confirm that the issue is still present in the release version? If so, can you please check if `javac` is in your path by just attempting to run `javac` in a console

**Comment by rlmhermans** [comment]
@cxcorp I just started IntelliJ, the problem is now gone. This was after a reboot, which I didn't try before. So either it's that, or setting up the dev environment fixed it. For that, I did add the IntelliJ plugin SDK, perhaps that helped?

Otherwise, I checked, I didn't have javac in my path. But the plugin already worked before I readded it.

**Comment by cxcorp** [comment]
@rlmhermans Hiya Ruud! I got your message on IRC. Thanks so much for the interest! I spoke with the maintainer, and if he gets the chance next week, he'll push out a new version with the fix to this issue to the plugin repository.

**Comment by cxcorp** [comment]
Just to add, if you need a fix urgently, it's possible to package the plugin into an JAR which can be installed manually with IntelliJ. You'd just clone the repo with the fix, set up the environment and deploy: https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/deploying_plugin.html

Of course, it's a bit of an inconvenience to have a bunch of students install the plugin manually, but it's an option until the update gets pushed.
