### ISSUE TITLE
Plugin loops forever when failing a Validation Case

### ISSUE THREAD

**Issue by cxcorp** [ohtu-intellij/tmc-intellij#106]
The plugin doesn't seem to handle exercises with TMC validation cases. Here's an example of what happens when submitting such an exercise:

![virhe](https://cloud.githubusercontent.com/assets/21111572/20670169/683c4aca-b580-11e6-9cad-1b05ae3690b9.png)

Stages 3 and 4 loop forever.

Example exercise with validation cases: `viikko11-Viikko11_181.HenkiloJaPerilliset` in course `hy-s2016-ohja` from `tmc.mooc.fi/hy`
Viewing the submission on TMC reveals the case which failed. In this case, it seems to be a linter that's failing.

![image](https://cloud.githubusercontent.com/assets/21111572/20670214/92ef3f34-b580-11e6-99be-5ea4bfbaae13.png)

**Comment by cxcorp** [comment]
I would speculate that this might work:

In [`SubmissionResultHandler::showResultMessage`](https://github.com/testmycode/tmc-intellij/blob/0a787477692232ae0ab3a2845e1beec0d109926b/tmc-plugin-intellij/src/main/java/fi/helsinki/cs/tmc/intellij/ui/submissionresult/SubmissionResultHandler.java#L18) from `src/main/java/fi/helsinki/cs/tmc/intellij/ui/submissionresult/SubmissionResultHandler.java`:

```
 public void showResultMessage(Exercise exercise, SubmissionResult result, Project project) {
     logger.info("Showing submission result message. @SubmissionResultHandler");

-    if (result.isAllTestsPassed()) {
+    if (result.isAllTestsPassed() && !result.validationsFailed()) {
         new SuccessfulSubmissionDialog(exercise, result, project);
     } else {
         new FailedSubmissionDialog(result, project);
     }
 }
```
[`FailedSubmissionDialog`](https://github.com/testmycode/tmc-intellij/blob/0a787477692232ae0ab3a2845e1beec0d109926b/tmc-plugin-intellij/src/main/java/fi/helsinki/cs/tmc/intellij/ui/submissionresult/FailedSubmissionDialog.java#L13) would also need to be updated to actually show the failed validations.

**Comment by cxcorp** [comment]
Nevermind, looks like this is either an [issue in the tmc-core](https://github.com/testmycode/tmc-core/issues/109).

```
2016-11-28 20:12:56 DEBUG AbstractSubmissionCommand:78 - Server done, parsing results
2016-11-28 20:12:56 INFO  CoreProgressObserver:28 - Setting progress status. @CoreProgressObserver
2016-11-28 20:12:56 WARN  SubmissionResultParser:68 - Failed to parse submission result
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 245 path $.validations.validationErrors.
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at fi.helsinki.cs.tmc.core.communication.serialization.SubmissionResultParser.parseFromJson(SubmissionResultParser.java:53)
	at fi.helsinki.cs.tmc.core.commands.Submit.call(Submit.java:82)
	at fi.helsinki.cs.tmc.core.commands.Submit.call(Submit.java:23)
	at fi.helsinki.cs.tmc.intellij.services.exercises.ExerciseUploadingService.getSubmissionResult(ExerciseUploadingService.java:112)
	at fi.helsinki.cs.tmc.intellij.services.exercises.ExerciseUploadingService.access$000(ExerciseUploadingService.java:25)
	at fi.helsinki.cs.tmc.intellij.services.exercises.ExerciseUploadingService$1.run(ExerciseUploadingService.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at fi.helsinki.cs.tmc.intellij.services.ThreadingService$1.run(ThreadingService.java:23)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 245 path $.validations.validationErrors.
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:387)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:189)
	... 29 more
2016-11-28 20:12:56 INFO  CoreProgressObserver:28 - Setting progress status. @CoreProgressObserver
2016-11-28 20:12:56 WARN  AbstractSubmissionCommand:91 - Error while updating submission status from server, continuing
```
