### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/plugins/gradle/service/project/wizard/GradleProjectOpenProcessor

### ISSUE THREAD

**Issue by pihvi** [ohtu-intellij/tmc-intellij#129]
After clicking download new exercises:

org/jetbrains/plugins/gradle/service/project/wizard/GradleProjectOpenProcessor
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: org/jetbrains/plugins/gradle/service/project/wizard/GradleProjectOpenProcessor
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:96)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.projectImport.ProjectOpenProcessor.getStrongImportProvider(ProjectOpenProcessor.java:76)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:111)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:48)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:36)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:76)
	at fi.helsinki.cs.tmc.intellij.services.exercises.NextExerciseFetcher.openFirst(NextExerciseFetcher.java:90)
	at fi.helsinki.cs.tmc.intellij.services.exercises.ExerciseDownloadingService$2.lambda$run$0(ExerciseDownloadingService.java:133)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/service/project/wizard/GradleProjectOpenProcessor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:138)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:76)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:158)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
	... 32 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.service.project.wizard.GradleProjectOpenProcessor PluginClassLoader[org.jetbrains.kotlin, 1.1.51-release-IJ2017.2-1] com.intellij.ide.plugins.cl.PluginClassLoader@7c6b7960
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
Caused by:

java.lang.NoClassDefFoundError: org/jetbrains/plugins/gradle/service/project/wizard/GradleProjectOpenProcessor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:268)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:237)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:138)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:76)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadImplementationClass(ExtensionComponentAdapter.java:158)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:66)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:73)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:119)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:246)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.projectImport.ProjectOpenProcessor.getStrongImportProvider(ProjectOpenProcessor.java:76)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:111)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:48)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:36)
	at fi.helsinki.cs.tmc.intellij.io.ProjectOpener.openProject(ProjectOpener.java:76)
	at fi.helsinki.cs.tmc.intellij.services.exercises.NextExerciseFetcher.openFirst(NextExerciseFetcher.java:90)
	at fi.helsinki.cs.tmc.intellij.services.exercises.ExerciseDownloadingService$2.lambda$run$0(ExerciseDownloadingService.java:133)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.gradle.service.project.wizard.GradleProjectOpenProcessor PluginClassLoader[org.jetbrains.kotlin, 1.1.51-release-IJ2017.2-1] com.intellij.ide.plugins.cl.PluginClassLoader@7c6b7960
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

**Comment by nygrenh** [comment]
Can you tell which course you're doing and which exercises you're trying to download?

**Comment by pihvi** [comment]
Cybersec course, securing part III: https://cybersecuritybase.github.io/securing/part3.html

tmc: https://tmc.mooc.fi/org/mooc/courses/267
exercises: https://tmc.mooc.fi/exercises/38534 and https://tmc.mooc.fi/exercises/38535

**Comment by pihvi** [comment]
Actually this seems to happen when opening the exercise as it happened again without downloading.
